export const Cart=[{
    src:true,
    name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt magna aliqua",
    brand: "dsvg",
    price: 1245,
    quantity: 3,
    total: 3735,
    status: false,
  },{
    src:true,
    name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt magna aliqua",
    brand: "dsvg",
    price: 1245,
    quantity: 3,
    total: 3735,
    status: false,
  },{
    src:true,
    name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt magna aliqua",
    brand: "dsvg",
    price: 1245,
    quantity: 3,
    total: 3735,
    status: false,
  },{
    src:true,
    name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt magna aliqua",
    brand: "dsvg",
    price: 1245,
    quantity: 3,
    total: 3735,
    status: false,
  },{
    src:true,
    name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt magna aliqua",
    brand: "dsvg",
    price: 1245,
    quantity: 3,
    total: 3735,
    status: false,
  },{
    src:true,
    name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt magna aliqua",
    brand: "dsvg",
    price: 1245,
    quantity: 3,
    total: 3735,
    status: false,
  }]